# Generated by Django 3.2.5 on 2021-07-22 08:51

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('Create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('Modify_timestamp', models.DateTimeField(auto_now=True)),
                ('Delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('national_code', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
