# Generated by Django 3.2.5 on 2021-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_receipt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='creat_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='final_price',
            field=models.FloatField(verbose_name='final price:'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='order',
            field=models.PositiveIntegerField(help_text="add number of order's", verbose_name="number of order's:"),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_discount',
            field=models.FloatField(verbose_name='total discount:'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_price',
            field=models.FloatField(verbose_name='total price:'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
