# Generated by Django 3.2.5 on 2021-07-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_merge_0004_auto_20210717_1816_0004_auto_20210717_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='deleted',
            field=models.BooleanField(verbose_name='delete'),
        ),
    ]
