# Generated by Django 3.2.5 on 2021-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0003_auto_20210713_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='discribe',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='parent',
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(blank=True, help_text='add description', max_length=50, null=True, verbose_name='description:'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='image',
            field=models.FileField(blank=True, help_text='image for item', null=True, upload_to='menu_items/images', verbose_name='add image:'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(help_text='name of category', max_length=50, verbose_name='Enter name:'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(blank=True, help_text='amount of discount', null=True, verbose_name='amount:'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, help_text='name of discount', max_length=100, null=True, verbose_name='name:'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='name',
            field=models.CharField(help_text='name of item', max_length=30, verbose_name='Enter name:'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(help_text='price of item', verbose_name='Enter price:'),
        ),
        migrations.AlterField(
            model_name='price',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
