# Generated by Django 3.2.5 on 2021-07-22 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_alter_receipt_deleted'),
        ('menu_items', '0005_auto_20210722_1319'),
        ('table', '0006_alter_table_status'),
        ('orders', '0005_merge_0004_auto_20210717_1816_0004_auto_20210717_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='deleted',
            field=models.BooleanField(verbose_name='delete'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='menu_items',
            field=models.ForeignKey(help_text='choice item you want', on_delete=django.db.models.deletion.CASCADE, to='menu_items.menuitems', verbose_name='item:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text="add number of item's", verbose_name='number:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='receipt',
            field=models.ForeignKey(help_text='choice receipt', on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt', verbose_name='receipt:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(help_text='choose status of order', on_delete=django.db.models.deletion.CASCADE, to='orders.orderstatus', verbose_name='status:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='table',
            field=models.ForeignKey(help_text='choice table', on_delete=django.db.models.deletion.CASCADE, to='table.table', verbose_name='table:'),
        ),
    ]
