# Generated by Django 3.2.5 on 2021-07-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20210713_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(help_text="add status for table's", max_length=30, verbose_name='status:'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(help_text='add number for table', verbose_name='table number:'),
        ),
    ]
