# Generated by Django 3.2.5 on 2021-07-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20210717_1816'),
        ('table', '0004_auto_20210717_1925'),
    ]

    operations = [
    ]
